version: '3'
services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./willgroup:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass